version: '3.9'
services:
  dcsm:
    build: .
    environment:
      - DCSM_KEYFILE=/example/key.private
      - DCSM_SECRETS_FILE=/example/secrets.encrypted
      - DCSM_SOURCE_FILE=/example/secrets.yaml
      - DCSM_TEMPLATE_DIR=/example/templates
    volumes:
      - ./example:/example

  tester:
    image: bash:latest
    command: ["bash", "/templates/confirm.sh"]
    depends_on:
      dcsm:
        condition: service_completed_successfully
    volumes:
      - ./templates:/templates
